### ISSUE TITLE
[Feature request] Extend Search Bar

### ISSUE THREAD

**Issue by mslourens** [openopus-org/openopus_api#1]
It would be nice to be able to search through all composers, artists and works with the same search bar at the top. Now you always have to look for the composer first and then search the work you want using a different search box.

**Comment by adrianosbr** [comment]
Omnisearch is in beta right now. It won't replace the work search right now (work search and omnisearch are different API endpoints). It will be used first in the iOS app, which is 70% done, and then it will be adopted by the web version.
