### ISSUE TITLE
Do you think is a good idea to use some framework as Lumen, Symfony or something more PHP7 style?

### ISSUE THREAD

**Issue by alex-grau** [openopus-org/openopus_api#2]
Hi,

I have a lot of free time and I think I can help on this project. I'm refactoring some old projects to DDD and I can try to do something with this one.

Are you interested?

**Comment by adrianosbr** [comment]
Hi! My code style is VERY old-fashioned, I know :) I used to be a developer back in the early 2000s and moved to sales/product management more than 10 years ago. 

Feel free to fork the project (that's the beauty of open source software!), refactor as you wish and we can discuss later on merging everything.

Meanwhile, I have to finish the API to make it ready for CRUD operations. And go for the front-end. It's a never ending project :)
