### ISSUE TITLE
Incorrect composers birth and death dates

### ISSUE THREAD

**Issue by Sef99** [openopus-org/openopus_api#6]
Hi! I noticed there's a problem with the composers birth and death dates. The year is correct, but for some reason the month and day all are 01-01.

**Comment by adrianosbr** [comment]
That's true. We couldn't feed precise day/month for most composers, but the field is already prepared for when it's done.

**Comment by Sef99** [comment]
Oh I see, thanks for the reply! Keep up the good work.
